root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o bin/app cmd/app/main.go"
bin = "bin/app"
include_ext = ["go", "yaml", "yml"]
exclude_dir = ["tmp", ".database", ".logs", ".idea", ".vscode", "api/swagger-ui"]
log = "air.log"
delay = 1000

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
