#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

STAGED_GO_FILES=$(git diff --cached --name-only -- '*.go')

if [[ $STAGED_GO_FILES != "" ]]; then
    for file in $STAGED_GO_FILES; do
        go fmt "$file"
        git add "$file"
    done
fi
