name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - '[0-9]+.x'
    tags:
      - '*'
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get dependencies
        run: |
          make deps

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Build
        run: |
          make build
          make build-docker-compose

      - name: Coverage
        run: make coverage
      - name: Coverage Upload
        uses: codecov/codecov-action@v3
        timeout-minutes: 5
        with:
          verbose: true
          files: ./coverage/coverage.out
          fail_ci_if_error: false

  deploy:
    needs:
      - test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy To Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP: ${{ secrets.HEROKU_APP }}
        run: |
          heroku container:login
          heroku container:push -a $HEROKU_APP web
          heroku container:release -a $HEROKU_APP web

  automerge:
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
